spring:
  application:
    name: spring-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/kudago
  jpa:
    properties:
      hibernate:
        show_sql: true
  devtools:
    restart:
      enabled: false

app:
  data-fetching:
    fetching-executor-service-threads-number: 4
    period: 5s
  currency-converter-base-url: http://localhost:8090/currencies
  kudago-rate-limit: 5

aspect:
  enabled: true

server:
  error:
    include-stacktrace: never
logging:
  level:
    sql: warn