spring:
  application:
    name: spring-app
  devtools:
    restart:
      enabled: true

logging:
  level:
    web: debug

app:
  data-fetching:
    fetching-executor-service-threads-number: 4
    period: 5s
  currency-converter-base-url: http://localhost:8090/currencies
  kudago-rate-limit: 5

aspect:
  enabled: true

server:
  error:
    include-stacktrace: never