name: Currency App Build

on:
  push:
    paths:
      - .github/workflows/currency-app-workflow.yml
      - currency-app/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Make gradlew executable
        working-directory: currency-app
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        working-directory: currency-app
        run: ./gradlew build

      - id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/currency-app/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
          title: Code Coverage
